[tools]
jq = "latest"
pnpm = "latest"
watchexec = "latest"
node = "latest"

[tasks.dev-backend]
description = "dev-backend"
dir = "backend"
run = """
  mise run dev
"""

[tasks.dev-frontend]
description = "dev-frontend"
dir = "frontend"
run = """
  mise run dev
"""

[tasks.gen]
description = "Generate code from openapi.yaml"
run = """
  node scripts/gen_gleam.ts
  cd frontend && pnpm gen
"""
